modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "familiarweapons"
version = "${version}"
displayName = "Familiar Weapons"
authors = "Partonetrain"
description = '''
Adds some equipment that may be familiar to you
'''
#logoFile = ""

[[dependencies.familiarweapons]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.familiarweapons]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.familiarweapons]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"